---
- name: Install OS packages
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - git

- name: Copy bin files
  ansible.builtin.copy:
    src: "{{ item.0 }}"
    dest: /home/{{ item.1.name }}/.bin/{{ item.0 }}
    owner: "{{ item.1.name }}"
    group: "{{ item.1.group }}"
    mode: 0755
  no_log: true
  with_nested:
    - [gh, ghq]
    - "{{ os.users }}"

# - name: Copy config files
#   ansible.builtin.template:
#     src: "{{ item }}"
#     dest: /home/{{ user }}/.{{ item | regex_replace('.j2$', '') }}
#     owner: "{{ user }}"
#     group: "{{ group }}"
#     mode: 0644
#   with_items:
#     - gitconfig.j2
