---
- name: Install OS packages
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - python3
    - python3-pip

- name: Install pip packages
  ansible.builtin.pip:
    name: "{{ item }}"
  with_items:
    - pipenv
