---
- name: Copy bin files
  ansible.builtin.copy:
    src: tmux
    dest: /home/{{ user }}/.bin/
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755

- name: Copy setting files
  ansible.builtin.copy:
    src: tmux.conf
    dest: /home/{{ user }}/.tmux.conf
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644

- name: Install Tmux Plugin Manager
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: /home/{{ user }}/.tmux/plugins/tpm
    update: false
  become: false
  tags:
    - skip_ansible_lint
