---
- name: Fail if OS version is not supported
  ansible.builtin.fail:
    msg: "{{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }} is currently not supported"
  when:
    - ansible_facts['distribution'] != "Rocky" or ansible_facts['distribution_major_version'] != "8"
    - ansible_facts['distribution'] != "Ubuntu" or ansible_facts['distribution_major_version'] != "22"
