---
- name: Install OS packages
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - fuse
    - "@Development tools"


- name: Copy font files
  ansible.builtin.copy:
    src: "{{ item.target }}"
    dest: /home/{{ user }}/.{{ item.target }}
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { target: fonts/, mode: "0755" }
