---
- name: Upgrade all OS packages
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_only: true
  when:
    - ansible_facts['distribution'] == "Rocky" or ansible_facts['distribution_major_version'] == "8"

- name: Upgrade all OS packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
  when:
    - ansible_facts['distribution'] == "Ubuntu" or ansible_facts['distribution_major_version'] == "22"
